create table sffo.categories (
  id integer generated by default as identity not null,
  name text not null,
  description text null,
  created_at timestamp without time zone null default now(),
  company_id bigint null,
  constraint categories_pkey primary key (id),
  constraint categories_id_key unique (id),
  constraint categories_company_id_fkey foreign KEY (company_id) references sffo.companies (id)
) TABLESPACE pg_default;

create table sffo.companies (
  id bigint generated by default as identity not null,
  name text null,
  constraint companies_pkey primary key (id)
) TABLESPACE pg_default;

create table sffo.customers (
  id integer generated by default as identity not null,
  name text not null,
  contact_number text null,
  address text null,
  created_at timestamp without time zone null default now(),
  company_id bigint null,
  constraint customers_pkey primary key (id),
  constraint customers_id_key unique (id),
  constraint customers_company_id_fkey foreign KEY (company_id) references sffo.companies (id)
) TABLESPACE pg_default;

create table sffo.product_change_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  product_id integer null,
  product_stock_id bigint null,
  message text null,
  user_id integer null,
  user_name text null,
  sales_order_id integer null,
  po_id integer null,
  constraint product_change_logs_pkey primary key (id),
  constraint product_change_logs_po_id_fkey foreign KEY (po_id) references sffo.purchase_orders (id) on delete CASCADE,
  constraint product_change_logs_product_id_fkey foreign KEY (product_id) references sffo.products (id) on delete CASCADE,
  constraint product_change_logs_product_stock_id_fkey foreign KEY (product_stock_id) references sffo.product_stocks (id) on delete CASCADE,
  constraint product_change_logs_sales_order_id_fkey foreign KEY (sales_order_id) references sffo.sales_orders (id) on delete CASCADE,
  constraint product_change_logs_user_id_fkey foreign KEY (user_id) references sffo.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table sffo.product_costs (
  id serial not null,
  product_id integer null,
  cost numeric not null,
  created_at timestamp without time zone null default now(),
  constraint product_costs_pkey primary key (id),
  constraint product_costs_product_id_fkey foreign KEY (product_id) references sffo.products (id) on delete CASCADE
) TABLESPACE pg_default;

create table sffo.product_stocks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  product_id integer null,
  cost numeric null,
  selling_price numeric null,
  quantity numeric null,
  remaining_quantity numeric null,
  purchase_date date null,
  purchase_order_id integer null,
  missing numeric null,
  company_id bigint null,
  hso_price numeric null,
  constraint product_stocks_pkey primary key (id),
  constraint product_stocks_company_id_fkey foreign KEY (company_id) references sffo.companies (id),
  constraint product_stocks_product_id_fkey foreign KEY (product_id) references sffo.products (id) on delete CASCADE,
  constraint product_stocks_purchase_order_id_fkey foreign KEY (purchase_order_id) references sffo.purchase_orders (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger product_quantity_update
after INSERT
or DELETE
or
update on sffo.product_stocks for EACH row
execute FUNCTION update_product_quantity ();

create table sffo.products (
  id integer generated by default as identity not null,
  name text not null,
  sku text null,
  description text null,
  current_cost numeric null,
  current_price numeric null,
  current_quantity integer null default 0,
  category_id integer null,
  unit text null,
  company_id bigint null,
  constraint products_pkey primary key (id),
  constraint products_id_key unique (id),
  constraint products_sku_key unique (sku),
  constraint products_category_id_fkey foreign KEY (category_id) references sffo.categories (id),
  constraint products_company_iod_fkey foreign KEY (company_id) references sffo.companies (id)
) TABLESPACE pg_default;

create table sffo.purchase_order_items (
  id integer generated by default as identity not null,
  purchase_order_id integer null,
  product_id integer null,
  quantity integer not null,
  cost numeric not null,
  price numeric null,
  created_at timestamp with time zone null default now(),
  delivered integer null default 0,
  to_deliver integer null default 0,
  constraint purchase_order_items_pkey primary key (id),
  constraint purchase_order_items_id_key unique (id),
  constraint purchase_order_items_product_id_fkey foreign KEY (product_id) references sffo.products (id),
  constraint purchase_order_items_purchase_order_id_fkey foreign KEY (purchase_order_id) references sffo.purchase_orders (id) on delete CASCADE
) TABLESPACE pg_default;

create table sffo.purchase_orders (
  id integer generated by default as identity not null,
  supplier_id integer null,
  status text not null default 'draft'::text,
  total_amount numeric not null default 0,
  payment_status text null default 'unpaid'::text,
  created_at timestamp without time zone null default now(),
  completed_at timestamp without time zone null,
  date text null,
  po_number text null,
  remarks text null,
  company_id bigint null,
  constraint purchase_orders_pkey primary key (id),
  constraint purchase_orders_id_key unique (id),
  constraint purchase_orders_company_id_fkey foreign KEY (company_id) references sffo.companies (id),
  constraint purchase_orders_supplier_id_fkey foreign KEY (supplier_id) references sffo.suppliers (id),
  constraint purchase_orders_payment_status_check check (
    (
      payment_status = any (
        array['paid'::text, 'partial'::text, 'unpaid'::text]
      )
    )
  ),
  constraint purchase_orders_status_check check (
    (
      status = any (
        array[
          'draft'::text,
          'approved'::text,
          'received'::text,
          'delivered'::text,
          'partially delivered'::text,
          'completed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;


create table sffo.purchase_payments (
  id integer generated by default as identity not null,
  purchase_order_id integer null,
  amount numeric not null,
  date date null,
  type text null,
  bank text null,
  due_date text null,
  constraint purchase_payments_pkey primary key (id),
  constraint purchase_payments_id_key unique (id),
  constraint purchase_payments_purchase_order_id_fkey foreign KEY (purchase_order_id) references sffo.purchase_orders (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger trg_update_purchase_payment_status
after INSERT
or DELETE
or
update on sffo.purchase_payments for EACH row
execute FUNCTION sffo.update_purchase_payment_status ();

create table sffo.sales_order_items (
  id integer generated by default as identity not null,
  sales_order_id integer null,
  quantity numeric not null,
  unit_price numeric not null,
  discount numeric null default 0,
  product_stock_id bigint null,
  total numeric null,
  created_at timestamp with time zone null default now(),
  product_id integer null,
  company_id bigint null,
  original_quantity numeric null,
  logs jsonb null,
  constraint sales_order_items_pkey primary key (id),
  constraint sales_order_items_id_key unique (id),
  constraint sales_order_items_company_id_fkey foreign KEY (company_id) references sffo.companies (id),
  constraint sales_order_items_product_id_fkey foreign KEY (product_id) references sffo.products (id) on delete CASCADE,
  constraint sales_order_items_product_stock_id_fkey foreign KEY (product_stock_id) references sffo.product_stocks (id) on delete CASCADE,
  constraint sales_order_items_sales_order_id_fkey foreign KEY (sales_order_id) references sffo.sales_orders (id) on delete CASCADE
) TABLESPACE pg_default;

create table sffo.sales_order_payments (
  id bigint generated by default as identity not null,
  sales_order_id integer null,
  date date null,
  amount numeric null,
  type text null,
  due_date text null,
  bank text null,
  company_id text null,
  constraint sales_order_payments_pkey primary key (id),
  constraint sales_order_payments_sales_order_id_fkey foreign KEY (sales_order_id) references sffo.sales_orders (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger trg_update_sales_order_payment_status
after INSERT
or
update on sffo.sales_order_payments for EACH row
execute FUNCTION sffo.update_sales_order_payment_status ();

create trigger trg_update_sales_order_payment_status_delete
after DELETE on sffo.sales_order_payments for EACH row
execute FUNCTION sffo.update_sales_order_payment_status ();

create table sffo.sales_orders (
  id integer generated by default as identity not null,
  customer_id integer null,
  status text not null default '''reserved''::text'::text,
  total_amount numeric not null default 0,
  discount_type text null default 'none'::text,
  discount_value numeric null default 0,
  created_at timestamp without time zone null default now(),
  completed_at timestamp without time zone null,
  po_number text null,
  date text null,
  payment_status text null default 'unpaid'::text,
  so_number text null,
  delivery_fee numeric null default '0'::numeric,
  company_id bigint null,
  other_charges text null,
  other_charges_amount numeric null,
  modified boolean null default false,
  constraint sales_orders_pkey primary key (id),
  constraint sales_orders_id_key unique (id),
  constraint sales_orders_company_id_fkey foreign KEY (company_id) references sffo.companies (id),
  constraint sales_orders_customer_id_fkey foreign KEY (customer_id) references sffo.customers (id),
  constraint sales_orders_discount_type_check check (
    (
      discount_type = any (
        array[
          'none'::text,
          'per_product'::text,
          'order_wide'::text
        ]
      )
    )
  ),
  constraint sales_orders_status_check check (
    (
      status = any (
        array[
          'draft'::text,
          'reserved'::text,
          'completed'::text,
          'approved'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table sffo.settings (
  id bigint generated by default as identity not null,
  shipping_company text null,
  shipping_address text null,
  shipping_contact_number text null,
  billing_company text null,
  billing_address text null,
  billing_contact_number text null,
  constraint settings_pkey primary key (id)
) TABLESPACE pg_default;

create table sffo.suppliers (
  id integer generated by default as identity not null,
  name text not null,
  contact_number text null,
  address text null,
  created_at timestamp without time zone null default now(),
  company_id bigint null,
  constraint suppliers_pkey primary key (id),
  constraint suppliers_id_key unique (id),
  constraint suppliers_company_id_fkey foreign KEY (company_id) references sffo.companies (id)
) TABLESPACE pg_default;

create table sffo.users (
  name text not null,
  password text not null,
  email text null,
  created_at timestamp without time zone null default now(),
  user_id uuid null,
  is_active boolean null default true,
  type text null,
  id integer generated by default as identity not null,
  company_id integer null,
  constraint users_pkey primary key (id),
  constraint users_id_key unique (id),
  constraint users_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

DROP TRIGGER IF EXISTS trg_update_sales_order_payment_status
ON sffo.sales_order_payments;


-- Trigger for insert/update
CREATE TRIGGER trg_update_sales_order_payment_status
AFTER INSERT OR UPDATE ON sffo.sales_order_payments
FOR EACH ROW
EXECUTE FUNCTION sffo.update_sales_order_payment_status();

-- Trigger for delete
CREATE TRIGGER trg_update_sales_order_payment_status_delete
AFTER DELETE ON sffo.sales_order_payments
FOR EACH ROW
EXECUTE FUNCTION sffo.update_sales_order_payment_status();


CREATE OR REPLACE FUNCTION sffo.update_sales_order_payment_status()
RETURNS TRIGGER AS $$
DECLARE
    so_id INTEGER;
    total_paid NUMERIC;
    order_total NUMERIC;
    has_pdc BOOLEAN;
BEGIN
    -- Figure out which sales_order_id to use (NEW for insert/update, OLD for delete)
    so_id := COALESCE(NEW.sales_order_id, OLD.sales_order_id);

    -- Get total order amount
    SELECT total_amount
    INTO order_total
    FROM sffo.sales_orders
    WHERE id = so_id;

    -- Sum of all payments for the order
    SELECT COALESCE(SUM(amount), 0)
    INTO total_paid
    FROM sffo.sales_order_payments
    WHERE sales_order_id = so_id;

    -- Check if any PDC payments exist
    SELECT EXISTS(
        SELECT 1
        FROM sffo.sales_order_payments
        WHERE sales_order_id = so_id
          AND type = 'PDC'
    ) INTO has_pdc;

    -- Update payment_status based on rules
    IF total_paid >= order_total
       AND has_pdc = FALSE
       AND EXISTS (
            SELECT 1
            FROM sffo.sales_orders
            WHERE id = so_id
              AND company_id = 3
       )
    THEN
        UPDATE sffo.sales_orders
        SET payment_status = 'Paid'
        WHERE id = so_id;
    ELSE
        -- Reset if payments don’t fully cover order
        UPDATE sffo.sales_orders
        SET payment_status = 'Unpaid'
        WHERE id = so_id;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
